### PR TITLE
Add Styles for Tags on the Frontend

### PR DESCRIPTION
**Pull request by simonv3**
# What's Changed

* Styles for tags on the front-end based on images sent to me by @langphil.
screenshot 2015-03-20 16 48 57

### CODE REVIEW

**Comment by simonv3** [comment]
Hmm, I'm not sure what the issue here is.

**Comment by pezholio** [comment]
Just wondering if it would be worth adding you as a contributor to our repos, rather than working on your forks - could be some Travis env issues - @Floppy whaddya reckon?

**Comment by simonv3** [comment]
@pezholio Wouldn't travis only run on the standard env stuff though?

**Comment by Floppy** [comment]
passes when travis has it variables.

**Pull request merged**
